name: Run load.py (LFW pairs)

on:
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'src/data/load.py'

jobs:
  load_raw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Fallback in case requirements step is skipped/misread
          python -c "import sklearn" || pip install scikit-learn

      - name: Sanity check sklearn
        run: |
          python -c "import sys, sklearn; print('Python:', sys.version); print('sklearn:', sklearn.__version__); import sklearn.datasets as d; print('fetch_lfw_pairs exists:', hasattr(d, 'fetch_lfw_pairs'))"

      - name: Run load.py (W&B off)
        env:
          WANDB_MODE: disabled
        run: python src/data/load.py --IdExecution ${{ github.run_number }}
