name: Load Raw Data like artifact to wandb

on:
  push:
    branches: [ main ]
    paths:
      - 'src/data/load.py'
      - 'src/__init__.py'          # optional: retrigger if package markers change
      - 'src/model/__init__.py'    # optional
      - 'requirements.txt'

jobs:
  load_raw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run load.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          WANDB_MODE: disabled
        run: |
          python -m src.data.load \
            --IdExecution ${{ github.run_number }} \
            --train_size 0.8 \
            --color false \
            --resize 1.0 \
            --data_home ./data
