name: Preprocess Raw Data like artifact to wandb

on:
  push:
    branches: [ main ]
    paths:
      - 'src/data/preprocess.py'
      - 'requirements.txt'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Run preprocess.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          WANDB_MODE: disabled
        run: python -m src.data.preprocess --IdExecution ${{ github.run_number }}